Testing branch
Scaleup-Excellenteam/exercise-3-4-debugging-logging-getting-into-a-large-codebase-hamzash10 pull request #2
Opened 2024-06-12 20:23 UTC by hamzash10

part-2 testing

2024-07-10 14:37 UTC, excellenteam-scaleup requested changes
Good job!
1. Missing most needed documentation
2. Assertions can be more indicative.

2024-07-10 14:37 UTC, excellenteam-scaleup commented on game_tests.py
> +        with patch.object(chess_engine.game_state, 'is_valid_piece', return_value=False):
missing doc

2024-07-10 14:37 UTC, excellenteam-scaleup commented on game_tests.py
> +
Consider splitting the tests into different files

2024-07-10 14:37 UTC, excellenteam-scaleup commented on game_tests.py
> +    def test_knight_valid_piece_takes_1(self):
Good division to 3 tests for the two functions.
Choose a more indicative name, replace "...takes_1" to "takes corner/center" accordingly, or use documentation to be more clear.

2024-07-10 14:37 UTC, excellenteam-scaleup commented on game_tests.py
> +    def set_full_takes(self):
It's good that you've separated a logic you're using into a different function, I'd just place it better, perhaps above all the tests. This way the code will "flow" more aesthetically : c;ass definition, functions, then all of the tests. Now it's test1-test1-test2-test2-function-test3-test3.

2024-07-10 14:37 UTC, excellenteam-scaleup commented on game_tests.py
> +    def set_full_takes(self):
Also, if you see that this functionality is to be used only internally you can consider making it an internal function (_set_full_takes)

2024-07-10 14:37 UTC, excellenteam-scaleup commented on game_tests.py
> +        # mocking the two functions to check only the logic of get_valid_piece_moves
Good documentation. Implement it throughout your code!

2024-07-20 05:41 UTC, hamzash10 commented on game_tests.py
> +        with patch.object(chess_engine.game_state, 'is_valid_piece', return_value=False):
documented all tests

2024-07-20 05:46 UTC, hamzash10 commented on game_tests.py
> +
done

2024-07-20 05:47 UTC, hamzash10 commented on game_tests.py
> +    def test_knight_valid_piece_takes_1(self):
sure, done documenting each function in great detail

2024-07-20 05:51 UTC, hamzash10 commented on game_tests.py
> +    def set_full_takes(self):
done

2024-07-20 05:52 UTC, hamzash10 commented on game_tests.py
> +        # mocking the two functions to check only the logic of get_valid_piece_moves
done

2024-08-18 13:18 UTC, excellenteam-scaleup approved these changes

2024-10-16 15:06 UTC, merged